sudo: required
dist: trusty
addons:
  apt:
    packages:
    - wget
    - curl
    - rpm
language: ruby
rvm:
- 2.1.5
env:
- PACKAGE_TARGET=deb
- PACKAGE_TARGET=rpm
install: bundle install
script:
- make
deploy:
  matrix:
  - provider: bintray
    file: ".bintray/deb.json"
    user: patdowney
    key:
      secure: XjJnffqCbLaZfqlv82ZxZDOOvpCeOLbOewYrGqtUXeBsYly/poHxHr/1fpHbJx/HlwiKA5BOZCqZOONzpPhDFiueti2ZBtGzVDYWuEIW79fSBBQpZ+5SnymhseXQLkZUHmlTZYox3f1sPcR5bvZ/nKK5fHKDpCr8Kqw5XYZI9mhNrgtxoY/iHLFTX0Rt8+j5RcqvGyOMhd51Z9tY2ZWv6FLIo2bWzx0+eiQX3+ddwO4IDJ9pw5kGqypuA9PCd7kVpZ5eoWNd9yUvZ2i4ZSDTCAr/RKoV3zY3j4dUFKriwV1eCx2ypMZ/8q7RuWezqtpWmgAHXaSLR1o3GQxidNCwKZxmAdzn/fkCu6BjYhZq2NMy0mZsLr0UESftNHin7GGowqjklyR7Cpe0/UCQKREi020ulICQ2gbNEr/8aZXpEU8Kz5CwJnCQJAc6mZXoAvi4Nkr36uChYjrMKEgASGqn+blP6q3CMU98/0Be9MVAuI47oIfz9XXYJVpo8FzmrdpsVWZwOubY3SANau8wxi6WN/b2E1hHAztshzXP5vosvTyxy5CREFu9QyBXU9FqHQZTTNot85TKouD3kFYrn9UFGouikplmP9oAhcAeXHKPiO3xGmGTIHzPYdL1VlwEMGARM5dLNQ47a1fdWw2I7idhnzpDZCyDj6CDondyHfyP45Q=
    on:
      condition: "$PACKAGE_TARGET = deb"
  - provider: bintray
    file: ".bintray/rpm.json"
    user: patdowney
    key:
      secure: XjJnffqCbLaZfqlv82ZxZDOOvpCeOLbOewYrGqtUXeBsYly/poHxHr/1fpHbJx/HlwiKA5BOZCqZOONzpPhDFiueti2ZBtGzVDYWuEIW79fSBBQpZ+5SnymhseXQLkZUHmlTZYox3f1sPcR5bvZ/nKK5fHKDpCr8Kqw5XYZI9mhNrgtxoY/iHLFTX0Rt8+j5RcqvGyOMhd51Z9tY2ZWv6FLIo2bWzx0+eiQX3+ddwO4IDJ9pw5kGqypuA9PCd7kVpZ5eoWNd9yUvZ2i4ZSDTCAr/RKoV3zY3j4dUFKriwV1eCx2ypMZ/8q7RuWezqtpWmgAHXaSLR1o3GQxidNCwKZxmAdzn/fkCu6BjYhZq2NMy0mZsLr0UESftNHin7GGowqjklyR7Cpe0/UCQKREi020ulICQ2gbNEr/8aZXpEU8Kz5CwJnCQJAc6mZXoAvi4Nkr36uChYjrMKEgASGqn+blP6q3CMU98/0Be9MVAuI47oIfz9XXYJVpo8FzmrdpsVWZwOubY3SANau8wxi6WN/b2E1hHAztshzXP5vosvTyxy5CREFu9QyBXU9FqHQZTTNot85TKouD3kFYrn9UFGouikplmP9oAhcAeXHKPiO3xGmGTIHzPYdL1VlwEMGARM5dLNQ47a1fdWw2I7idhnzpDZCyDj6CDondyHfyP45Q=
    on:
      condition: "$PACKAGE_TARGET = rpm"
